version: "3"

services:
  api:
    build:
        context: .
    ports:
      - "8080:8080"
    container_name: api
    depends_on:
      - mongo
    volumes:
      - ./api:/go/src/github.com/ono5/study-hacker/api
    command: realize start --run
  frontend:
    build:
        context: .
        dockerfile: "./Dockerfile-nodejs"
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - api
    volumes:
      - ./frontend:/frontend
    command: >
      sh -c "npm run serve"
      # sh -c "while :; do sleep 10; done"
    stdin_open: true

  mongo:
    image: mongo
    container_name: mongo
